### ISSUE TITLE
Sync-gateway data dump throw unhandled promise exception

### ISSUE THREAD

**Issue by shashanktomar** [bentonam/fakeit#152]
While dumping data to sync-gateway, i am getting this error:
```
[18:37:41] ✖ error: { Error: connect ECONNRESET 127.0.0.1:4985
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4985 }
(node:63267) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: connect ECONNRESET 127.0.0.1:4985
```
Some of the documents are missed because of this.

**Comment by alburdette619** [comment]
I am having this same issue.  I frequently get cross reference errors in my application due to documents not getting written.

**Comment by tjbenton** [comment]
This might be happening because too many files are trying to write to the server at a time. Try running your `fakeit` command with `--limit 5`. This would be a temp fix until we can fix the real issue

**Comment by alburdette619** [comment]
#154
