### ISSUE TITLE
Limit option is broken

### ISSUE THREAD

**Issue by alburdette619** [bentonam/fakeit#154]
Including `--limit X`, where X is an integer, in the fakeit command errors out and states that it should be a number.

For example: `fakeit sync-gateway --server http://localhost:4984 --bucket mobile-app ./data/models --limit 5`

```
Error: The limit option must be a number
    at Object.limit (.../node_modules/fakeit/dist/output/index.js:503:13)
    at .../node_modules/fakeit/dist/output/index.js:413:24
    at Object.to.each (.../node_modules/to-js/dist/to.js:1066:16)
    at Output.validateOutputOptions (.../node_modules/fakeit/dist/output/index.js:408:22)
    at new Output (.../node_modules/fakeit/dist/output/index.js:93:11)
    at Fakeit._callee$ (.../node_modules/fakeit/dist/index.js:124:26)
    at tryCatch (.../node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (.../node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (.../node_modules/regenerator-runtime/runtime.js:117:21)
    at step (.../node_modules/fakeit/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

**Comment by tjbenton** [comment]
fixing the issue in #155. Should be published in a couple hours
